name: keel
description: A ViewModel based architecture for Flutter
version: 1.0.0
homepage: https://github.com/arklabsnz/keel-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ">=0.26.0  <1.0.0"
  provider: ">=5.0.0-nullsafety.5  <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
